---
title: "Recortar e reamostrar as áreas de análise escolhidas"
author: "Oliveira-Santos, Claudinei"
date: "19 de setembro de 2017"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 12
    fig_width: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Pacotes, funções e configurações do R
```{r PackFuncConf, message=FALSE, warning=FALSE, echo=TRUE}
#Packages, functions and configurations
options(scipen = 999)
library(raster)
library(rgdal)
library(scales)
library(ggplot2)
library(gpclib)
library(maptools)
library(rasterVis)
gpclibPermit()
```

### Áreas escolhidas

Foram escolhidas três áreas para analisar o processo de reamostragem da versão oito (v8) do mapa síntese de pastagem gerado pelo Lapig. 
<br/> - Cerrado (*Bacia Hidrógrafica do Rio Vermelho*)
<br/> - Amazônia
<br/> - Mata Atlântica

### Recortar imagem de NDVI para as áreas escolhidas
```{r cropAreas, echo=TRUE, cache=TRUE}
#Shape = Grid do Brasil 111 km/2
gridBr111km <- shapefile("dados/gridBrLim111km/Grid_BrLim_111_km_wgs84.shp")

#Raster = Imagem de ndvi para o Brasil, referência para reamostragem
rst <- raster('/hds/dados_work/DATASAN/raster/NDVI/BRASIL/pa_br_ndvi_250_2017001_lapig.tif')

#Poligonos da areas amotrais (referencia é o shp)
id <- c(AM = 655, MA = 944, BHRV = 1227)

#Crop areas
for(i in 1:length(id)){
  cat("Crop", names(id[i]), "\n")
  
  crop(rst,
       gridBr111km[gridBr111km$OBJECTID == id[i], ],
       filename = paste0("dados/ndviSample/","NDVI_Sample_", names(id[i]), "_",id[i],".tif"),
       overwrite = TRUE)
}
```



```{r Fig1 gridAreas, echo=TRUE, cache=TRUE, fig.height=6, fig.width=6, fig.align="center"}
#Grid fortify
gridBr111km@data$id <- gridBr111km$OBJECTID
fortfyGridBr = fortify(gridBr111km, region = "id")

#Areas analisadas
ggplot(data = fortfyGridBr) +
  geom_polygon(aes(x = long, fill = id , y = lat, group = group),
               fill = alpha("gray", 0.5),
               colour = "gray") + 
  geom_polygon(data = fortfyGridBr[fortfyGridBr$id %in% id, ],
               aes(x = long, fill = id , y = lat, group = group),
               fill = "red", colour = "black") + 
  labs(x = "longitude", y = 'latitude') +
  ggtitle("Áreas para analisar mascara e pastagem")+
  guides(colour=TRUE, fill = TRUE) + #remove legenda
  coord_equal() + 
  theme_light(base_size = 14,
              base_family = "")
```


### Reamostrar as áreas escolhidas para análise
```{r resampleAreas, echo=TRUE, cache=TRUE}
#Area escolhida na Amazônia rasterizada para 10 metros
lsfPast <- Sys.glob(file.path("dados/pastSample","*.tif"))
lsfNdvi <- Sys.glob(file.path("dados/ndviSample/","*.tif"))

#Resample areas
for(i in 1:length(id)){
  cat("Resample", names(id[i]), "\n")
  
  rstRsmp <- projectRaster(
    raster(
      grep(id[i], lsfPast, value = TRUE)),
    raster(
      grep(id[i], lsfNdvi, value = TRUE)),
    filename = paste0("results/pastResample/","Pastagem_Resample_", names(id[i]), "_",id[i],".tif"),
    overwrite = TRUE)
}
```



```{r Fig2 areasSelec, echo=TRUE, cache=TRUE, fig.height=6, fig.width=18, fig.align="center"}
#Plot areas selecionadas
lsfNdvi <- Sys.glob(file.path("dados/ndviSample/","*.tif"))
lsfPast <- Sys.glob(file.path("dados/pastSample","*.tif"))
lsfPastResamp <- Sys.glob(file.path("results/pastResample","*.tif"))

for(i in 1:length(id)){
  cat("Resample", names(id[i]), "\n")
  par(mfrow = c(1, 3))
  plot(raster(lsfNdvi[i]), main = "NDVI 250 m")
  plot(raster(lsfPastResamp[i]), main = "Pastagem 250 m", col = "red")
  plot(raster(lsfPast[i]), main = "Pastagem 10 m", col = "darkgreen")
}
```

